import { elementList, optionalElement, requiredElement } from './dom-query.js';

export function attach(ctx) {
  const { document } = ctx;
  const elements = {
    chart: requiredElement(document, '#portfolio-chart'),
    stockChart: requiredElement(document, '#stock-chart'),
    donutTooltip: requiredElement(document, '#donut-tooltip'),
    legend: requiredElement(document, '#holdings-legend'),
    stockLegend: requiredElement(document, '#stock-legend'),
    portfolioTotal: requiredElement(document, '#portfolio-total'),
    portfolioTotalCenter: requiredElement(document, '#portfolio-total-center'),
    stockTotalCenter: requiredElement(document, '#stock-total-center'),
    stockDetail: requiredElement(document, '#stock-detail'),
    stockDetailTitle: requiredElement(document, '#stock-detail-title'),
    stockDetailClose: requiredElement(document, '#stock-detail-close'),
    monthlyHead: requiredElement(document, '#monthly-head'),
    monthlyTracking: requiredElement(document, '#monthly-tracking'),
    monthlySummary: requiredElement(document, '#monthly-summary'),
    ytdSubtitle: requiredElement(document, '#ytd-subtitle'),
    historyStats: requiredElement(document, '#history-stats'),
    historyChart: requiredElement(document, '#history-chart'),
    historyStatus: requiredElement(document, '#history-status'),
    historyGranularity: requiredElement(document, '#history-granularity'),
    historySubtitle: requiredElement(document, '#history-subtitle'),
    historyRangeButtons: elementList(document, '[data-history-range]'),
    historyTooltip: requiredElement(document, '#history-tooltip'),
    historyEventPanel: requiredElement(document, '#history-event-panel'),
    ledgerRows: requiredElement(document, '#ledger-rows'),
    ledgerFilterSymbol: document.querySelector('#ledger-filter-symbol'),
    ledgerFilterOrigin: document.querySelector('#ledger-filter-origin'),
    ledgerFilterType: document.querySelector('#ledger-filter-type'),
    ledgerFilterFrom: document.querySelector('#ledger-filter-from'),
    ledgerFilterTo: document.querySelector('#ledger-filter-to'),
    ledgerTotals: document.querySelector('#ledger-totals'),
    ledgerFilterInfo: document.querySelector('#ledger-filter-info'),
    ledgerSelectionCount: document.querySelector('#ledger-selection-count'),
    selectVisibleTransactions: document.querySelector('#select-visible-transactions'),
    deselectAllTransactions: document.querySelector('#deselect-all-transactions'),
    deleteSelectedTransactions: document.querySelector('#delete-selected-transactions'),
    editSelectedTransaction: document.querySelector('#edit-selected-transaction'),
    ledgerPagination: document.querySelector('#ledger-pagination'),
    performanceSummary: document.querySelector('#performance-summary'),
    backupList: document.querySelector('#backup-list'),
    createBackup: document.querySelector('#create-backup'),
    openImportDialog: document.querySelector('#open-import-dialog'),
    openImportDialogToolbar: document.querySelector('#open-import-dialog-toolbar'),
    ledgerExportXlsx: document.querySelector('#ledger-export-xlsx'),
    ledgerExportDialog: document.querySelector('#ledger-export-dialog'),
    ledgerExportDialogClose: document.querySelector('#ledger-export-dialog-close'),
    ledgerExportSummary: document.querySelector('#ledger-export-summary'),
    ledgerExportWarning: document.querySelector('#ledger-export-warning'),
    ledgerExportWarningText: document.querySelector('#ledger-export-warning-text'),
    ledgerExportConfirm: document.querySelector('#ledger-export-confirm'),
    ledgerExportCancel: document.querySelector('#ledger-export-cancel'),
    confirmActionDialog: document.querySelector('#confirm-action-dialog'),
    confirmActionTitle: document.querySelector('#confirm-action-title'),
    confirmActionMessage: document.querySelector('#confirm-action-message'),
    confirmActionClose: document.querySelector('#confirm-action-close'),
    confirmActionCancel: document.querySelector('#confirm-action-cancel'),
    confirmActionConfirm: document.querySelector('#confirm-action-confirm'),
    dividendAlert: document.querySelector('#dividend-alert'),
    dividendAlertCount: document.querySelector('#dividend-alert-count'),
    dividendDraftDialog: document.querySelector('#dividend-draft-dialog'),
    dividendDraftClose: document.querySelector('#dividend-draft-close'),
    dividendDraftSummary: document.querySelector('#dividend-draft-summary'),
    dividendDraftRows: document.querySelector('#dividend-draft-rows'),
    adminManager: document.querySelector('#admin-manager'),
    adminDialog: document.querySelector('#admin-dialog'),
    adminDialogClose: document.querySelector('#admin-dialog-close'),
    adminCancel: document.querySelector('#admin-cancel'),
    updateCheck: document.querySelector('#update-check'),
    updateDownload: document.querySelector('#update-download'),
    updateDockerCommands: document.querySelector('#update-docker-commands'),
    updateReleaseNotes: document.querySelector('#update-release-notes'),
    updateCurrentVersion: document.querySelector('#update-current-version'),
    updateLatestVersion: document.querySelector('#update-latest-version'),
    updateDbStatus: document.querySelector('#update-db-status'),
    updateLastCheck: document.querySelector('#update-last-check'),
    updateNotice: document.querySelector('#update-notice'),
    updateDockerOutput: document.querySelector('#update-docker-output'),
    proRequestLink: document.querySelector('#pro-request-link'),
    negativeRedToggle: document.querySelector('#negative-red-toggle'),
    languageSelect: document.querySelector('#language-select'),
    ledgerPageSize: document.querySelector('#ledger-page-size'),
    dateFormatSelect: document.querySelector('#date-format-select'),
    weekStartSelect: document.querySelector('#week-start-select'),
    operationsPreferenceControls: document.querySelector('#operations-preference-controls'),
    historyPreferenceControls: document.querySelector('#history-preference-controls'),
    returnBreakdownPreferenceControls: document.querySelector('#return-breakdown-preference-controls'),
    dashboardLayoutPreferenceControls: document.querySelector('#dashboard-layout-preference-controls'),
    returnBreakdownSectionWrapper: document.querySelector('#return-breakdown-section-wrapper'),
    returnBreakdownToggle: document.querySelector('#return-breakdown-toggle'),
    proPreferencesCard: document.querySelector('#pro-preferences-card'),
    importDialog: document.querySelector('#import-dialog'),
    importDialogClose: document.querySelector('#import-dialog-close'),
    importCancel: document.querySelector('#import-cancel'),
    importForm: document.querySelector('#import-form'),
    importFile: document.querySelector('#import-file'),
    importFileZone: document.querySelector('#import-file-zone'),
    importSource: document.querySelector('#import-source'),
    importProBanners: document.querySelector('#import-pro-banners'),
    importSheetField: document.querySelector('#import-sheet-field'),
    importSheet: document.querySelector('#import-sheet'),
    importMapping: document.querySelector('#import-mapping'),
    importContent: document.querySelector('#import-content'),
    importPreview: document.querySelector('#import-preview'),
    importCommit: document.querySelector('#import-commit'),
    importFeedback: document.querySelector('#import-feedback'),
    importPreviewOutput: document.querySelector('#import-preview-output'),
    importMappingRequired: document.querySelector('#import-mapping-required'),
    importBatches: document.querySelector('#import-batches'),
    importTemplateDownload: document.querySelector('#import-template-download'),
    importDownloadTemplate: document.querySelector('#import-download-template'),
    headerActions: document.querySelector('.header-actions'),
    onboardingWizard: document.querySelector('#onboarding-wizard'),
    instrumentManager: document.querySelector('#instrument-manager'),
    instrumentDialog: document.querySelector('#instrument-dialog'),
    instrumentDialogClose: document.querySelector('#instrument-dialog-close'),
    instrumentCancel: document.querySelector('#instrument-cancel'),
    instrumentRows: document.querySelector('#instrument-rows'),
    instrumentPositionFilter: document.querySelector('#instrument-position-filter'),
    instrumentFilterSymbol: document.querySelector('#instrument-filter-symbol'),
    instrumentFilterYahoo: document.querySelector('#instrument-filter-yahoo'),
    instrumentFilterName: document.querySelector('#instrument-filter-name'),
    instrumentThGroup: document.querySelector('#instrument-th-group'),
    instrumentFilterGroup: document.querySelector('#instrument-filter-group'),
    instrumentFilterCurrency: document.querySelector('#instrument-filter-currency'),
    instrumentSelectionCount: document.querySelector('#instrument-selection-count'),
    selectVisibleInstruments: document.querySelector('#select-visible-instruments'),
    deselectAllInstruments: document.querySelector('#deselect-all-instruments'),
    deleteSelectedInstruments: document.querySelector('#delete-selected-instruments'),
    instrumentDeleteDialog: document.querySelector('#instrument-delete-dialog'),
    instrumentDeleteDialogClose: document.querySelector('#instrument-delete-dialog-close'),
    instrumentDeleteCancel: document.querySelector('#instrument-delete-cancel'),
    instrumentDeleteConfirm: document.querySelector('#instrument-delete-confirm'),
    instrumentDeletePreview: document.querySelector('#instrument-delete-preview'),
    groupRows: document.querySelector('#group-rows'),
    groupSelectionCount: document.querySelector('#group-selection-count'),
    selectVisibleGroups: document.querySelector('#select-visible-groups'),
    deselectAllGroups: document.querySelector('#deselect-all-groups'),
    deleteSelectedGroups: document.querySelector('#delete-selected-groups'),
    instrumentGroupsEnabled: document.querySelector('#instrument-groups-enabled'),
    instrumentGroupsSection: document.querySelector('#instrument-groups-section'),
    newGroupName: document.querySelector('#new-group-name'),
    newGroupColor: document.querySelector('#new-group-color'),
    createGroup: document.querySelector('#create-group'),
    liquiditySummary: document.querySelector('#liquidity-summary'),
    liquidityAccounts: document.querySelector('#liquidity-accounts'),
    liquidityFeedback: document.querySelector('#liquidity-feedback'),
    newLiquidityName: document.querySelector('#new-liquidity-name'),
    newLiquidityBalance: document.querySelector('#new-liquidity-balance'),
    newLiquidityCurrency: document.querySelector('#new-liquidity-currency'),
    newLiquidityColor: document.querySelector('#new-liquidity-color'),
    createLiquidityAccount: document.querySelector('#create-liquidity-account'),
    newInstrumentSymbol: document.querySelector('#new-instrument-symbol'),
    newInstrumentYahoo: document.querySelector('#new-instrument-yahoo'),
    newInstrumentName: document.querySelector('#new-instrument-name'),
    newInstrumentType: document.querySelector('#new-instrument-type'),
    newInstrumentCommodity: document.querySelector('#new-instrument-commodity'),
    newInstrumentCurrency: document.querySelector('#new-instrument-currency'),
    newInstrumentGroup: document.querySelector('#new-instrument-group'),
    newInstrumentColor: document.querySelector('#new-instrument-color'),
    createInstrument: document.querySelector('#create-instrument'),
    priceStatus: document.querySelector('#price-status'),
    marketProviderStatus: document.querySelector('#market-provider-status'),
    marketProviderStatusTooltip: document.querySelector('#market-provider-status-tooltip'),
    addPosition: document.querySelector('#add-position'),
    removePosition: document.querySelector('#remove-position'),
    appVersion: document.querySelector('#app-version'),
    autoCalendar: document.querySelector('#auto-calendar'),
    autoDialog: document.querySelector('#auto-dialog'),
    autoDialogClose: document.querySelector('#auto-dialog-close'),
    autoCancel: document.querySelector('#auto-cancel'),
    autoForm: document.querySelector('#auto-form'),
    autoPlanList: document.querySelector('#auto-plan-list'),
    autoFeedback: document.querySelector('#auto-feedback'),
    autoSubmit: document.querySelector('#auto-submit'),
    wizardDialog: document.querySelector('#wizard-dialog'),
    wizardDialogClose: document.querySelector('#wizard-dialog-close'),
    wizardCancel: document.querySelector('#wizard-cancel'),
    wizardForm: document.querySelector('#wizard-form'),
    wizardModeManual: document.querySelector('#wizard-mode-manual'),
    wizardModeImport: document.querySelector('#wizard-mode-import'),
    wizardImportEntry: document.querySelector('#wizard-import-entry'),
    wizardOpenImport: document.querySelector('#wizard-open-import'),
    wizardUseGroup: document.querySelector('#wizard-use-group'),
    wizardGroupNameField: document.querySelector('#wizard-group-name-field'),
    wizardGroupColorField: document.querySelector('#wizard-group-color-field'),
    wizardGroupName: document.querySelector('#wizard-group-name'),
    wizardGroupColor: document.querySelector('#wizard-group-color'),
    brandPaletteEnabled: document.querySelector('#brand-palette-enabled'),
    wizardGroupDistribution: document.querySelector('#wizard-group-distribution'),
    wizardGroupMonthly: document.querySelector('#wizard-group-monthly'),
    wizardGroupExpandable: document.querySelector('#wizard-group-expandable'),
    wizardInstrumentSymbol: document.querySelector('#wizard-instrument-symbol'),
    wizardInstrumentYahoo: document.querySelector('#wizard-instrument-yahoo'),
    wizardInstrumentName: document.querySelector('#wizard-instrument-name'),
    wizardInstrumentType: document.querySelector('#wizard-instrument-type'),
    wizardInstrumentCommodity: document.querySelector('#wizard-instrument-commodity'),
    wizardInstrumentCurrency: document.querySelector('#wizard-instrument-currency'),
    wizardInstrumentColor: document.querySelector('#wizard-instrument-color'),
    wizardAddTransaction: document.querySelector('#wizard-add-transaction'),
    wizardTransactionDate: document.querySelector('#wizard-transaction-date'),
    wizardTransactionEuros: document.querySelector('#wizard-transaction-euros'),
    wizardTransactionShares: document.querySelector('#wizard-transaction-shares'),
    wizardTransactionCommission: document.querySelector('#wizard-transaction-commission'),
    wizardAddPlan: document.querySelector('#wizard-add-plan'),
    wizardPlanAmount: document.querySelector('#wizard-plan-amount'),
    wizardPlanFrequency: document.querySelector('#wizard-plan-frequency'),
    wizardPlanDay: document.querySelector('#wizard-plan-day'),
    wizardPlanDayField: document.querySelector('#wizard-plan-day-field'),
    wizardPlanWeekday: document.querySelector('#wizard-plan-weekday'),
    wizardPlanWeekdayField: document.querySelector('#wizard-plan-weekday-field'),
    wizardPlanStart: document.querySelector('#wizard-plan-start'),
    wizardPlanConfirmField: document.querySelector('#wizard-plan-confirm-field'),
    wizardPlanConfirmRetroactive: document.querySelector('#wizard-plan-confirm-retroactive'),
    wizardPlanPreview: document.querySelector('#wizard-plan-preview'),
    wizardFeedback: document.querySelector('#wizard-feedback'),
    wizardSubmit: document.querySelector('#wizard-submit'),
    addDialog: document.querySelector('#add-dialog'),
    addDialogClose: document.querySelector('#add-dialog-close'),
    addCancel: document.querySelector('#add-cancel'),
    addForm: document.querySelector('#add-form'),
    operationTitle: document.querySelector('#operation-title'),
    operationSubtitle: document.querySelector('#operation-subtitle'),
    operationType: document.querySelector('#operation-type'),
    tickerInputField: document.querySelector('#ticker-input-field'),
    tickerSelectField: document.querySelector('#ticker-select-field'),
    addTicker: document.querySelector('#add-ticker'),
    operationCreateInstrument: document.querySelector('#operation-create-instrument'),
    removeTicker: document.querySelector('#remove-ticker'),
    addDate: document.querySelector('#add-date'),
    addCalculationSection: document.querySelector('#add-calculation-section'),
    addEntryModeTabs: document.querySelector('#add-entry-mode-tabs'),
    addEntryModeInputs: document.querySelectorAll('input[name="add-entry-mode"]'),
    addPriceField: document.querySelector('#add-price-field'),
    addPriceCurrencyField: document.querySelector('#add-price-currency-field'),
    addFxField: document.querySelector('#add-fx-field'),
    addSharesField: document.querySelector('#add-shares-field'),
    addEurosField: document.querySelector('#add-euros-field'),
    addEuros: document.querySelector('#add-euros'),
    addShares: document.querySelector('#add-shares'),
    addPrice: document.querySelector('#add-price'),
    addPriceCurrency: document.querySelector('#add-price-currency'),
    addFx: document.querySelector('#add-fx'),
    addCommissionField: document.querySelector('#add-commission-field'),
    addCommission: document.querySelector('#add-commission'),
    addNote: document.querySelector('#add-note'),
    addFeedback: document.querySelector('#add-feedback'),
    addAmountHint: document.querySelector('#add-amount-hint'),
    transactionPreview: document.querySelector('#transaction-preview'),
    addSubmit: document.querySelector('#add-submit'),
    transactionEditDialog: document.querySelector('#transaction-edit-dialog'),
    transactionEditForm: document.querySelector('#transaction-edit-form'),
    transactionEditClose: document.querySelector('#transaction-edit-close'),
    transactionEditCancel: document.querySelector('#transaction-edit-cancel'),
    transactionEditSummary: document.querySelector('#transaction-edit-summary'),
    transactionEditDate: document.querySelector('#transaction-edit-date'),
    transactionEditShares: document.querySelector('#transaction-edit-shares'),
    transactionEditPrice: document.querySelector('#transaction-edit-price'),
    transactionEditCurrency: document.querySelector('#transaction-edit-currency'),
    transactionEditFx: document.querySelector('#transaction-edit-fx'),
    transactionEditCommission: document.querySelector('#transaction-edit-commission'),
    transactionEditNote: document.querySelector('#transaction-edit-note'),
    transactionEditFeedback: document.querySelector('#transaction-edit-feedback'),
    transactionEditPreview: document.querySelector('#transaction-edit-preview'),
    transactionEditSubmit: document.querySelector('#transaction-edit-submit'),
    refreshPrices: document.querySelector('#refresh-prices'),
    balanceToggle: document.querySelector('#balance-toggle'),
    themeToggle: document.querySelector('#theme-toggle'),
    bootOverlay: document.querySelector('#boot-overlay'),
    bootRetry: optionalElement(document, '#boot-retry'),
  };

  Object.assign(ctx, { elements });
}
