export function attach(ctx) {
  const eurFormatter = new Intl.NumberFormat('es-ES', { style: 'currency', currency: 'EUR' });
  const sharesFormatter = new Intl.NumberFormat('es-ES', { maximumFractionDigits: 2 });
  const cryptoSharesFormatter = new Intl.NumberFormat('es-ES', { maximumFractionDigits: 6 });
  const historyRangeConfig = {
    all: { granularity: 'weekly', years: null },
    '5y': { granularity: 'weekly', years: 5 },
    '2y': { granularity: 'weekly', years: 2 },
    '1y': { granularity: 'daily', years: 1 },
    ytd: { granularity: 'daily', years: 0 },
  };
  const assetColors = {};
  const state = {
    summary: null,
    onboarding: null,
    monthly: null,
    history: null,
    historyRange: 'ytd',
    historyCache: {},
    historyRequestId: 0,
    historyAbortController: null,
    autoPlans: [],
    autoPlanDrafts: [],
    transactions: [],
    instruments: [],
    groups: [],
    backups: [],
    importPreview: null,
    importRowActions: {},
    importRowMappings: {},
    importRowEdits: {},
    importInstrumentChoices: {},
    importConfirmedSteps: {},
    importOperationFilter: 'all',
    importStep: 'file',
    importWorkflowBusy: false,
    importInstrumentValidationAttempted: false,
    importBatches: [],
    importFileMeta: null,
    groupsEnabled: true,
    initialLoadComplete: false,
    transactionPreviewOk: false,
    version: null,
    expandedGroupId: null,
    hideBalances: false,
    negativeRed: true,
    dateFormat: 'dd/mm/yyyy',
    weekStart: 'monday',
    instrumentPositionFilter: 'all',
    instrumentFilters: {
      symbol: '',
      yahoo: '',
      name: '',
      group: '',
      currency: '',
    },
    selectedInstrumentSymbols: [],
    visibleInstrumentSymbols: [],
    selectedGroupIds: [],
    visibleGroupIds: [],
    selectedTransactionIds: [],
    visibleTransactionIds: [],
    ledgerPageSize: 1000,
    pendingTransactionDelete: [],
    returnToOperationDialogAfterInstrumentCreate: false,
    historyEventFilters: { mode: 'custom', assetTypes: ['stock', 'etf', 'crypto'], transactionTypes: ['add', 'remove'] },
  };

  Object.assign(ctx, { eurFormatter, sharesFormatter, cryptoSharesFormatter, historyRangeConfig, assetColors, state });
}
